version: '3.8'

services:
  lineage-auditor:
    container_name: legacy-sat-auditor
    build:
      context: .
      dockerfile: Dockerfile
    image: criptografia/legacy-sat-auditor:latest
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=development
      - PORT=5555
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - auditor-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: satsranges-tunnel
    # Overriding the command to just "sleep" so it stays alive
    command: ["sleep", "infinity"] 
    networks:
      - auditor-network
networks:
  auditor-network:
    driver: bridge